### ISSUE TITLE
Better instructions?

### ISSUE THREAD

**Issue by ArakTaiRoth** [laelath/hack-match-bot#3]
Would you be able to write more involved instructions on how to get setup to run this?

**Comment by laelath** [comment]
You just gotta build and and run it with cargo. tbh this project is more here to show off that I did it, it lacks any and UI or helpful error reporting

**Comment by RunninglVlan** [comment]
I'd also note that this only runs on Linux. I tried building it for Windows through GitHub Codespaces, but it uses x11rb, which works only on Linux. Then I tried running it via WSL - x11rb worked, but since it can't access Windows-native windows, it errored out again.
