### ISSUE TITLE
error: process didn't exit successfully

### ISSUE THREAD

**Issue by CuWO4** [laelath/hack-match-bot#4]
# problem occured:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DisplayParsingError', src\main.rs:109:51
**error**: process didn't exit successfully: `target\release\hack_match_bot.exe` (exit code: 101)

# what did i do:
after running `cargo build --release` and `cargo run --release`, the problem occured.

# adding info:
**operating system**: win 10 professional edition 21H2
**rustc version**: 1.70.0 (90c541806 2023-05-31)
**cargo version**: 1.70.0 (ec8a8a0ca 2023-04-25)

**Comment by laelath** [comment]
it uses X11 to capture the game window so only works with the linux version of the game
